version: '3.1'

services:
  mysql-user:
    image: mysql:latest
    container_name: mysql-user
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: user
    ports:
      - "3307:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql

  mysql-identity:
    image: mysql:latest
    container_name: mysql-identity
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: identity
    ports:
      - "3308:3306"
    volumes:
      - mysql-identity-data:/var/lib/mysql

  mysql-product:
    image: mysql:latest
    container_name: mysql-product
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: product
    ports:
      - "3309:3306"
    volumes:
      - mysql-product-data:/var/lib/mysql

  mysql-order:
    image: mysql:latest
    container_name: mysql-order
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: order
    ports:
      - "3310:3306"
    volumes:
      - mysql-order-data:/var/lib/mysql

volumes:
  mysql-user-data:
  mysql-identity-data:
  mysql-product-data:
  mysql-order-data:
